plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
    alias(libs.plugins.google.services)
    alias(libs.plugins.firebase.crashlytics)
    alias(libs.plugins.baselineprofile)
}

android {
    namespace = "com.karalo.karalo"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.karalo.karalo"
        minSdk = 24
        targetSdk = 35
        versionCode = 1
        versionName = "0.1.0"
        testInstrumentationRunner = "com.karalo.karalo.HiltTestRunner"
    }

    signingConfigs {
        create("release") {
            val keystorePath =
                System.getenv("RELEASE_KEYSTORE_PATH") ?: providers.gradleProperty("RELEASE_KEYSTORE_PATH").orNull
            if (keystorePath != null) {
                storeFile = file(keystorePath)
                storePassword =
                    System.getenv("RELEASE_KEYSTORE_PASSWORD")
                        ?: providers.gradleProperty("RELEASE_KEYSTORE_PASSWORD").orNull
                keyAlias = System.getenv("RELEASE_KEY_ALIAS") ?: providers.gradleProperty("RELEASE_KEY_ALIAS").orNull
                keyPassword =
                    System.getenv("RELEASE_KEY_PASSWORD") ?: providers.gradleProperty("RELEASE_KEY_PASSWORD").orNull
            }
        }
    }

    buildTypes {
        release {
            // Measured on a Chromecast with Google TV: without R8 the app shipped every dependency's
            // code whole (57.5MB of dex, ~94MB installed with ART's copies); with it, 7MB of dex and
            // ~21MB installed. Keep rules for what R8 can't see through are in proguard-rules.pro.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            // Only applies the release signing config when secrets are actually present locally/in CI
            // (see README "Secrets" section) — an unsigned build is still useful for local testing.
            if (signingConfigs.getByName("release").storeFile != null) {
                signingConfig = signingConfigs.getByName("release")
            }
        }
    }

    buildFeatures {
        compose = true
    }

    // androidTestImplementation(:core-testing) pulls in JUnit5, and several of its jars each
    // bundle their own META-INF/LICENSE.md — same fix as core-testing/build.gradle.kts.
    packaging {
        resources {
            excludes += setOf("META-INF/LICENSE*", "META-INF/NOTICE*")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        // NewPipeExtractor calls java.util.stream.Collectors APIs (e.g. toUnmodifiableList())
        // that ART only implements on API 33+; desugaring backports them for our minSdk 24.
        isCoreLibraryDesugaringEnabled = true
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

// Generated by :baselineprofile (see that module) and merged into release builds so ART AOT-
// compiles the app's Compose/scroll-animation hot paths at install time instead of JIT-compiling
// them live on first use -- see docs/adr/ and this module's own doc for the real-device jank this
// was found to cause. `automaticGenerationDuringBuild` is deliberately false: generating it
// requires a connected device/emulator, which CI's release workflow (a plain Ubuntu runner) has
// no way to provide. Regenerate manually (`./gradlew :baselineprofile:generateBaselineProfile`)
// and commit the result whenever a major user-facing flow changes meaningfully -- see
// CONTRIBUTING.md.
baselineProfile {
    automaticGenerationDuringBuild = false
}

dependencies {
    baselineProfile(project(":baselineprofile"))

    implementation(project(":core-common"))
    implementation(project(":core-ui"))
    implementation(project(":core-karaoke"))
    implementation(project(":feature-search"))
    implementation(project(":feature-player"))
    implementation(project(":feature-home"))
    implementation(project(":feature-playlists"))
    implementation(project(":feature-history"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)

    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.foundation)
    implementation(libs.compose.runtime)
    implementation(libs.compose.material.icons.extended)
    debugImplementation(libs.compose.ui.tooling)

    implementation(libs.tv.material)
    implementation(libs.navigation.compose)
    implementation(libs.coil.compose)
    implementation(libs.androidx.profileinstaller)

    implementation(libs.hilt.android)
    implementation(libs.hilt.navigation.compose)
    ksp(libs.hilt.compiler)

    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.crashlytics)
    implementation(libs.firebase.analytics)

    testImplementation(project(":core-testing"))
    testImplementation(libs.junit5.jupiter.api)
    testRuntimeOnly(libs.junit5.jupiter.engine)
    testImplementation(libs.mockk)

    coreLibraryDesugaring(libs.desugar.jdk.libs)

    androidTestImplementation(project(":core-testing"))
    androidTestImplementation(project(":youtube-client"))
    androidTestImplementation(platform(libs.compose.bom))
    androidTestImplementation(libs.compose.ui.test.junit4)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.espresso.core)
    androidTestImplementation(libs.hilt.android.testing)
    kspAndroidTest(libs.hilt.compiler)
    debugImplementation(libs.compose.ui.test.manifest)
}
