// Adapted from TeamNewPipe/NewPipe (GPL-3.0), app/src/main/java/org/schabi/newpipe/util/potoken/PoTokenGenerator.kt
//
// Deviates from upstream by using suspend functions instead of RxJava3's Single — this project
// has no RxJava dependency anywhere and is Coroutines-only throughout.
package com.karalo.youtubeclient.internal.potoken

import java.io.Closeable

/**
 * Generates poTokens for a single BotGuard VM session (see [PoTokenWebView], the only
 * implementation — this interface exists just to keep [PoTokenWebView]'s WebView-driving
 * internals out of [WebViewPoTokenProvider]).
 */
internal interface PoTokenGenerator : Closeable {
    /**
     * Generates a poToken for the provided identifier, using the `integrityToken` and
     * `webPoSignalOutput` previously obtained in the initialization of [PoTokenWebView]. Can be
     * called multiple times.
     */
    suspend fun generatePoToken(identifier: String): String

    /**
     * @return whether the `integrityToken` is expired, in which case all tokens generated by
     * [generatePoToken] will be invalid
     */
    fun isExpired(): Boolean
}
